---

- name: Check if conf.d directory already exist
  stat:
    path: "/etc/nginx/conf.d"
  register: confd
  when: (app_role != "vagrant")

- name: Make conf.d directory exists
  file:
    path: "/etc/nginx/conf.d"
    state: directory
  when: (app_role != "vagrant" and confd.stat.exists == False )

- name: Deploy site configs
  template:
    src: conf.d/uwsgi.conf.j2
    dest: /etc/nginx/conf.d/{{ http_hostname }}.conf
  notify: Restart Nginx
  when: app_role != "vagrant"

- name: Deploy site configs vagrant
  template:
    src: conf.d/vagrant.conf.j2
    dest: /etc/nginx/conf.d/default.conf
  notify: Restart Nginx
  when: app_role == "vagrant"

- name: Check if SSL certs already exist
  stat:
    path: /etc/dhparams.pem
  register: stat_ssl

- name: Generate dhparams
  shell: openssl dhparam -out /etc/dhparams.pem 2048
  become: yes
  when: stat_ssl.stat.exists == False and app_role != "production"