# Generated by Django 2.0 on 2019-02-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_orderreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderreport',
            name='date_placed',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
