---
version: '2'
services:
  #pstgresql
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=p@ssw0rd24
      - POSTGRES_USER=testimo
      - POSTGRES_DB=testimo
    ports:
      - 5432:5432
    volumes:
      - ../testimo-data:/var/lib/postgresql/data

  #solr
  solr:
    image: solr:6.5
    ports:
      - "8983:8983"
    volumes:
      - ./solr-core/testimo:/opt/solr/server/solr/mycores/testimo
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - testimo
  memcached:
    image: memcached
    ports:
      - "11211:11211"

  #rabbitmq
  rabbit:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_VHOST: "/"
    labels:
      NAME: "rabbitmq"

    # Enable volume is have configuration, create directory rabbitmq : mkdir ../rabbitmq/
    # volumes:
    #   - "../rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins"
    #- "../rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro"
