# Generated by Django 2.0 on 2019-03-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0015_auto_20181215_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='oss_image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
