# Generated by Django 2.0 on 2019-03-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0016_productimage_oss_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='original',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/products/%Y/%m/', verbose_name='Original'),
        ),
    ]
