# Generated by Django 2.0 on 2019-02-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_auto_20190222_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcetype',
            name='amount_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='IPay88 Amount Fee'),
        ),
        migrations.AlterField(
            model_name='sourcetype',
            name='bank_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='IPay88 Bank Fee'),
        ),
        migrations.AlterField(
            model_name='sourcetype',
            name='percent_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='IPay88 Percent Fee'),
        ),
    ]
