---
- hosts:
    - testimo-omnibus

  vars_files:
    - environments/vault_vars.yml

  vars:
    workdir: "/srv/{{ app_user }}/www/src/{{ app_user }}"
    venv: "/srv/{{ app_name }}/venv"
    db_pass: "{{ tes_db_pass }}"
    access_key: "{{ oss_ak }}"
    secret_access: "{{ oss_sk }}"
    python_user: root
    project_name: "{{ app_name }}"
    #rabbitmq vars
    rabbitpass: "{{ rabbit_pass }}"

    #somax.conn
    max_con: 65535

    #gdn_fee
    gdn_fee: "8"

    APP_ENV_PREFIX: TES

    #celery vars
    celery_appname: "{{ app_user }}"
    celery_logfile: celery.log
    celery_workdir: /srv/{{ app_user }}/www/src/{{ app_user }}

#NewRelic configuration
    newrelic_write_logfile: True #True And False
    app_full_name: "Bhisma - Testimo" #Display Application Name Newrelic

#roles active
  roles:
    - role: apps/submodule
      when: app_role == "vagrant"
    - role: common/ubuntu-bionic
    - role: apps/python
    - role: apps/nginx
      use_brotli: "True"
    - apps/npm
    - role: apps/postgresql
      when: app_role != "production"
    - { role: lang/java, java_version: 8 }
    - role: apps/solr
      when: app_role != "production"
    - role: 'apps/rabbitmq'
      listeners_tcp_default: 5672
      rabbitmq_user: "rabbit_admin"
      rabbitmq_pass: "{{ rabbitpass }}"
      management_listener_port: 15672
      when: app_role != "production"
    - role: 'uwsgi-app'
      http_static_locations:
        - http_path: '/static'
          dir_path: '{{ workdir }}/static'
        - http_path: '/uploads'
          dir_path: '{{ workdir }}/uploads'
    - role: apps/newrelic
      when: app_role == "production"
  become: yes

# Docs Server
# - hosts: gm-docs
#   gather_facts: no
#   vars:
#     #Ansible Variables
#     app_user: tes
#     sphinx_project_name: tes-web #this variables must same with repo name
#     app_role: "{{ app_role_sphinx }}" #this variable add in jenkinsfile
#     source_docs_host: tes-omnibus #inventory hostname from server source Documentation
#
#   roles:
#     - apps/gm-docs
