# Generated by Django 2.0 on 2019-02-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_auto_20190211_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcetype',
            name='gdn_amount_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='GDN Amount Fee'),
        ),
        migrations.AddField(
            model_name='sourcetype',
            name='gdn_bank_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='GDN Bank Fee'),
        ),
        migrations.AddField(
            model_name='sourcetype',
            name='gdn_percent_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='GDN Percent Fee'),
        ),
        migrations.AlterField(
            model_name='sourcetype',
            name='percent_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Percent Fee'),
        ),
    ]
